# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/TaterComms/issues"

[[mods]]
modId = "tatercomms"
version = "${file.jarVersion}"
displayName = "TaterComms"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/TaterComms/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/TaterComms"
logoFile= "../TaterComms.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A simple, cross API plugin that bridges communication between servers.
'''

# Forge Dependency
[[dependencies.tatercomms]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.tatercomms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
