---
version: 1

# Discord bot configuration
discord:
  enabled: true
  token: ""
  guildId: ""

  # Server to Discord Channel mapping
  channels:
    # in the format of: serverName: channelId
    example: "123456789012345678"

# Remote websocket configuration (for servers that you can't run behind a proxy)
# Fun fact: if you're having issues running Forge 1.13+ behind a proxy, check out Ambassador: https://github.com/adde0109/Ambassador
# Short explanation: The 1.13 update changed the way that Forge initializes and syncs mod/datapack data with the server, this causes issues with the way that the proxy works.
remote:
  enabled: false
  primary: false
  url: "ws://localhost:5483"


# ServerName for standalone servers (Bukkit, Fabric, or Forge)
server:
  name: "example"

