---
version: 1

# Discord bot configuration
discord:
  enabled: true
  token: ""
  guildId: ""

  # Server to Discord Channel mapping
  channels:
    # in the format of: serverName: channelId
    example: "123456789012345678"

# Remote
remote:


# ServerName for standalone servers (Bukkit, Fabric, or Forge)
server:
  name: "example"

