# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/TaterComms/issues"

[[mods]]
modId = "tatercomms"
version = "${file.jarVersion}"
displayName = "TaterComms"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/TaterComms/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/TaterComms"
logoFile= "../TaterComms.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A simple, cross API plugin that bridges communication between servers, using built-in Proxy methods, Discord channels and websockets.
'''

# Forge Dependency
[[dependencies.tatercomms]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.tatercomms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

# LuckPerms Dependency
[[dependencies.tatercomms]]
modId = "luckperms"
mandatory = false
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "SERVER"
